[versions]
kotlin = "2.3.0"

plasmovoice = "2.1.9"
lombok = "1.18.44"
fabric-loader = "0.17.3"
fabric-loom = "1.15-SNAPSHOT"
buildconfig = "5.7.0"

[libraries]
plasmovoice = { module = "su.plo.voice.api:client", version.ref = "plasmovoice" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
fabricloader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
loom = { id = "fabric-loom", version.ref = "fabric-loom" }
buildconfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
